version: '3'
services:
  backend:
    build: ./Blogger-Backend
    ports:
      - "3000:3000"
    
    environment:
      - NODE_ENV=production



  frontend:
    build: ./Blogger
    ports:
      - "80:80"
    
    depends_on:
      - backend


